### ISSUE TITLE
tmPreference file for sublime block commenting

### ISSUE THREAD

**Issue by eephillip** [zeek/zeek-sublime#4]
Not sure how this can be auto generated by packageDev, if at all, but dropping the following into the package gives access to commenting/block commenting, in sublime.

`Comments (Zeek).tmPreferences`
```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Comments</string>
    <key>scope</key>
    <string>source.zeek</string>
    <key>settings</key>
    <dict>
        <key>shellVariables</key>
        <array>
            <dict>
                <key>name</key>
                <string>TM_COMMENT_START</string>
                <key>value</key>
                <string># </string>
            </dict>
            <dict>
                <key>name</key>
                <string>TM_COMMENT_DISABLE_INDENT_2</string>
                <key>value</key>
                <string>yes</string>
            </dict>
        </array>
    </dict>
</dict>
</plist>
```

**Comment by jsiwek** [comment]
Thanks, added a `Comments.tmPreferences` in `master` and `1.0.3` now.  I removed the `TM_COMMENT_DISABLE_INDENT_2` key since I don't it wasn't doing anything due to the `_2` part of it, plus indenting comments *is* generally the typical coding style/convention anyway.
